// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         chain_id: 1,
 *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
 *         token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
 *         options: {
 *             include_metadata: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface GetPositionProfileDexRequest {
    /** Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /** Wallet address of the position to retrieve. */
    wallet: string;
    /** Token address of the position to retrieve. */
    token: string;
    options?: Prism.api.EvmDexPositionProfilePayloadOptions;
}
