// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         chain_id: 1,
 *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
 *     }
 */
export interface GetSwapsDexRequest extends Prism.api.PayloadPagination {
    /** Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /** Wallet address to filter swaps by. */
    wallet?: string;
    /** Token address to filter swaps by. */
    token?: string;
    /** Pool address to filter swaps by. */
    pool?: string;
}
