// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         chain_id: 1,
 *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
 *         options: {
 *             include_metadata: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface GetWalletProfileDexRequest {
    /** Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /** Wallet address to retrieve the profile for. */
    wallet: string;
    options?: Prism.api.EvmDexWalletProfilePayloadOptions;
}
