// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         chain_id: 1,
 *         query: {
 *             text: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
 *             fields: ["token_address"]
 *         },
 *         sort: {
 *             field: "metrics.1d.usd_volume",
 *             direction: "desc"
 *         },
 *         options: {
 *             include_metadata: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface SearchTokenProfilesDexRequest extends Prism.api.PayloadPagination {
    /** Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    query?: Prism.api.EvmDexTokenProfileSearchPayloadQueryField;
    filter?: Prism.api.EvmDexProfileSearchPayloadFilter;
    sort?: Prism.api.EvmDexProfileSearchPayloadSort;
    options?: Prism.api.EvmDexTokenProfilePayloadOptions;
}
