// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         chain_id: 1,
 *         query: {
 *             text: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
 *             fields: ["wallet_address"]
 *         },
 *         sort: {
 *             field: "metrics.7d.cumulative_pnl",
 *             direction: "desc"
 *         },
 *         options: {
 *             include_metadata: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface SearchWalletProfilesDexRequest extends Prism.api.PayloadPagination {
    /** Numeric EVM chain ID to query. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    query?: Prism.api.EvmDexWalletProfileSearchPayloadQuery;
    filter?: Prism.api.EvmDexProfileSearchPayloadFilter;
    sort?: Prism.api.EvmDexProfileSearchPayloadSort;
    options?: Prism.api.EvmDexWalletProfilePayloadOptions;
}
