// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../../../../../BaseClient.js";
import {
    type NormalizedClientOptionsWithAuth,
    normalizeClientOptionsWithAuth,
} from "../../../../../../../../BaseClient.js";
import { mergeHeaders } from "../../../../../../../../core/headers.js";
import * as core from "../../../../../../../../core/index.js";
import * as environments from "../../../../../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../../../../../errors/index.js";
import * as Prism from "../../../../../../../index.js";

export declare namespace DexClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class DexClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<DexClient.Options>;

    constructor(options: DexClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * Returns a wallet profile for a specific wallet.
     *
     * @param {Prism.api.evm.GetWalletProfileDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getWalletProfile({
     *         chain_id: 1,
     *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public getWalletProfile(
        request: Prism.api.evm.GetWalletProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexWalletProfile> {
        return core.HttpResponsePromise.fromPromise(this.__getWalletProfile(request, requestOptions));
    }

    private async __getWalletProfile(
        request: Prism.api.evm.GetWalletProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexWalletProfile>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/wallets/get-profile",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexWalletProfile, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/wallets/get-profile",
        );
    }

    /**
     * Filter, query, and sort wallet profiles based on specified metrics and conditions.
     *
     * @param {Prism.api.evm.SearchWalletProfilesDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.searchWalletProfiles({
     *         limit: 10,
     *         chain_id: 1,
     *         query: {
     *             text: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
     *             fields: ["wallet_address"]
     *         },
     *         sort: {
     *             field: "metrics.7d.cumulative_pnl",
     *             direction: "desc"
     *         },
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public searchWalletProfiles(
        request: Prism.api.evm.SearchWalletProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.evm.SearchWalletProfilesDexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchWalletProfiles(request, requestOptions));
    }

    private async __searchWalletProfiles(
        request: Prism.api.evm.SearchWalletProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.evm.SearchWalletProfilesDexResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/wallets/search-profiles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Prism.api.evm.SearchWalletProfilesDexResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/wallets/search-profiles",
        );
    }

    /**
     * Returns the profile for a specific token.
     *
     * @param {Prism.api.evm.GetTokenProfileDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getTokenProfile({
     *         chain_id: 1,
     *         token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public getTokenProfile(
        request: Prism.api.evm.GetTokenProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexTokenProfile> {
        return core.HttpResponsePromise.fromPromise(this.__getTokenProfile(request, requestOptions));
    }

    private async __getTokenProfile(
        request: Prism.api.evm.GetTokenProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexTokenProfile>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/tokens/get-profile",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexTokenProfile, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/tokens/get-profile",
        );
    }

    /**
     * Filter, query, and sort token profiles based on specified metrics and conditions.
     *
     * @param {Prism.api.evm.SearchTokenProfilesDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.searchTokenProfiles({
     *         limit: 10,
     *         chain_id: 1,
     *         query: {
     *             text: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
     *             fields: ["token_address"]
     *         },
     *         sort: {
     *             field: "metrics.1d.usd_volume",
     *             direction: "desc"
     *         },
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public searchTokenProfiles(
        request: Prism.api.evm.SearchTokenProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.evm.SearchTokenProfilesDexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchTokenProfiles(request, requestOptions));
    }

    private async __searchTokenProfiles(
        request: Prism.api.evm.SearchTokenProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.evm.SearchTokenProfilesDexResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/tokens/search-profiles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Prism.api.evm.SearchTokenProfilesDexResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/tokens/search-profiles",
        );
    }

    /**
     * Returns a position profile for a specific wallet-token pair.
     *
     * @param {Prism.api.evm.GetPositionProfileDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getPositionProfile({
     *         chain_id: 1,
     *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
     *         token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public getPositionProfile(
        request: Prism.api.evm.GetPositionProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexPositionProfile> {
        return core.HttpResponsePromise.fromPromise(this.__getPositionProfile(request, requestOptions));
    }

    private async __getPositionProfile(
        request: Prism.api.evm.GetPositionProfileDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexPositionProfile>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/positions/get-profile",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexPositionProfile, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/positions/get-profile",
        );
    }

    /**
     * Filter, query, and sort position profiles based on specified metrics and conditions.
     *
     * @param {Prism.api.evm.SearchPositionProfilesDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.searchPositionProfiles({
     *         limit: 10,
     *         chain_id: 1,
     *         sort: {
     *             field: "metrics.7d.pnl",
     *             direction: "desc"
     *         },
     *         options: {
     *             include_metadata: true,
     *             include_metrics: ["7d"]
     *         }
     *     })
     */
    public searchPositionProfiles(
        request: Prism.api.evm.SearchPositionProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.evm.SearchPositionProfilesDexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__searchPositionProfiles(request, requestOptions));
    }

    private async __searchPositionProfiles(
        request: Prism.api.evm.SearchPositionProfilesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.evm.SearchPositionProfilesDexResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/profiles/positions/search-profiles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Prism.api.evm.SearchPositionProfilesDexResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/profiles/positions/search-profiles",
        );
    }

    /**
     * Returns trades for a wallet and/or token on a single chain.
     *
     * @param {Prism.api.evm.GetTradesDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getTrades({
     *         limit: 20,
     *         chain_id: 1,
     *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
     *     })
     */
    public getTrades(
        request: Prism.api.evm.GetTradesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.evm.GetTradesDexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTrades(request, requestOptions));
    }

    private async __getTrades(
        request: Prism.api.evm.GetTradesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.evm.GetTradesDexResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/trades/get-trades",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.evm.GetTradesDexResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/trades/get-trades",
        );
    }

    /**
     * Returns swaps for a combination of wallet, token and/or pool.
     *
     * @param {Prism.api.evm.GetSwapsDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getSwaps({
     *         limit: 20,
     *         chain_id: 1,
     *         wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
     *     })
     */
    public getSwaps(
        request: Prism.api.evm.GetSwapsDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.evm.GetSwapsDexResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSwaps(request, requestOptions));
    }

    private async __getSwaps(
        request: Prism.api.evm.GetSwapsDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.evm.GetSwapsDexResponse>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/swaps/get-swaps",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.evm.GetSwapsDexResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/evm/dex/swaps/get-swaps");
    }

    /**
     * Returns prices for one or more tokens or pools.
     *
     * @param {Prism.api.evm.GetPriceDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getPrice({
     *         chain_id: 1,
     *         tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"]
     *     })
     */
    public getPrice(
        request: Prism.api.evm.GetPriceDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexPrice[]> {
        return core.HttpResponsePromise.fromPromise(this.__getPrice(request, requestOptions));
    }

    private async __getPrice(
        request: Prism.api.evm.GetPriceDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexPrice[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/prices/get-price",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexPrice[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/evm/dex/prices/get-price");
    }

    /**
     * Returns price stats for one or more tokens or pools.
     *
     * @param {Prism.api.evm.GetPriceStatsDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getPriceStats({
     *         chain_id: 1,
     *         tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"]
     *     })
     */
    public getPriceStats(
        request: Prism.api.evm.GetPriceStatsDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexPriceStats[]> {
        return core.HttpResponsePromise.fromPromise(this.__getPriceStats(request, requestOptions));
    }

    private async __getPriceStats(
        request: Prism.api.evm.GetPriceStatsDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexPriceStats[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/prices/get-price-stats",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexPriceStats[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/prices/get-price-stats",
        );
    }

    /**
     * Returns price candles for a specific token and/or pool.
     *
     * @param {Prism.api.evm.GetPriceCandlesDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getPriceCandles({
     *         chain_id: 1,
     *         token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
     *         from: "2026-04-27T00:00:00Z",
     *         to: "2026-04-27T01:00:00Z",
     *         interval: 60
     *     })
     */
    public getPriceCandles(
        request: Prism.api.evm.GetPriceCandlesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexPriceCandle[]> {
        return core.HttpResponsePromise.fromPromise(this.__getPriceCandles(request, requestOptions));
    }

    private async __getPriceCandles(
        request: Prism.api.evm.GetPriceCandlesDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexPriceCandle[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/prices/get-price-candles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexPriceCandle[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/prices/get-price-candles",
        );
    }

    /**
     * Returns price history for one or more tokens or pools.
     *
     * @param {Prism.api.evm.GetPriceHistoryDexRequest} request
     * @param {DexClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Prism.api.BadRequestError}
     * @throws {@link Prism.api.UnauthorizedError}
     * @throws {@link Prism.api.ForbiddenError}
     * @throws {@link Prism.api.TooManyRequestsError}
     * @throws {@link Prism.api.InternalServerError}
     *
     * @example
     *     await client.api.evm.dex.getPriceHistory({
     *         chain_id: 1,
     *         tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
     *         from: "2026-04-27T00:00:00Z",
     *         to: "2026-04-27T01:00:00Z",
     *         interval: 3600
     *     })
     */
    public getPriceHistory(
        request: Prism.api.evm.GetPriceHistoryDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): core.HttpResponsePromise<Prism.api.EvmDexPriceHistory[]> {
        return core.HttpResponsePromise.fromPromise(this.__getPriceHistory(request, requestOptions));
    }

    private async __getPriceHistory(
        request: Prism.api.evm.GetPriceHistoryDexRequest,
        requestOptions?: DexClient.RequestOptions,
    ): Promise<core.WithRawResponse<Prism.api.EvmDexPriceHistory[]>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PrismEnvironment.Production,
                "v1/evm/dex/prices/get-price-history",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Prism.api.EvmDexPriceHistory[], rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Prism.api.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Prism.api.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Prism.api.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Prism.api.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Prism.api.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PrismError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/evm/dex/prices/get-price-history",
        );
    }
}
