// This file was auto-generated by Fern from our API Definition.

import type * as ApiClient from "../../../../../index.js";

export interface GetSwapsDexResponse extends ApiClient.PaginatedResponse {
    data?: ApiClient.SolanaDexSwap[] | undefined;
}
