// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../../../../../index.js";

export interface SearchWalletProfilesDexResponse extends PrismApi.PaginatedResponse {
    data?: PrismApi.SolanaDexWalletProfile[] | undefined;
}
