// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../../../../../index.js";

export interface SearchTokenProfilesDexResponse extends PrismApi.PaginatedResponse {
    data?: PrismApi.SolanaDexTokenProfile[] | undefined;
}
