// This file was auto-generated by Fern from our API Definition.

export interface SubscribeEvmDexTradesParams {
    /** Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /** The token addresses to filter by. Leave empty to subscribe to all tokens on the chain. */
    token_addresses?: string[] | undefined;
    /** The wallet addresses to filter by. Leave empty to subscribe to all wallets on the chain. */
    wallet_addresses?: string[] | undefined;
}
