// This file was auto-generated by Fern from our API Definition.

export interface SubscribeEvmAssetsTransfersParams {
    /** Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /** The from addresses to filter by. Leave empty to subscribe to all from addresses on the chain. */
    from_addresses?: string[] | undefined;
    /** The to addresses to filter by. Leave empty to subscribe to all to addresses on the chain. */
    to_addresses?: string[] | undefined;
}
