// This file was auto-generated by Fern from our API Definition.

export interface SubscribeEvmDexPoolsParams {
    /** Numeric EVM chain ID to receive updates for. See [Supported Chains](/documentation/evm/overview#supported-chains). */
    chain_id: number;
    /**
     * The pool addresses to filter by. Unlike the other EVM subscriptions, an empty list
     * matches no pools rather than all of them, so at least one address is required to
     * receive updates.
     */
    pool_addresses?: string[] | undefined;
}
