// This file was auto-generated by Fern from our API Definition.

export interface SubscribeSolanaAssetsBalanceChangesParams {
    /** The owner addresses to filter by. Leave empty to subscribe to all owners. */
    owner_addresses?: string[] | undefined;
    /** The token addresses to filter by. Leave empty to subscribe to all tokens. */
    token_addresses?: string[] | undefined;
}
