// This file was auto-generated by Fern from our API Definition.

export interface SubscribeSolanaDexPositionProfilesParams {
    /** The position addresses to filter by. Leave empty to subscribe to all positions. */
    position_addresses?: string[] | undefined;
}
