// This file was auto-generated by Fern from our API Definition.

export interface SubscribeSolanaAssetsTransfersParams {
    /** The from addresses to filter by. Leave empty to subscribe to all from addresses. */
    from_addresses?: string[] | undefined;
    /** The to addresses to filter by. Leave empty to subscribe to all to addresses. */
    to_addresses?: string[] | undefined;
}
