// This file was auto-generated by Fern from our API Definition.

import * as PrismApi from "../../../src/api/index";
import { PrismApiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("DexClient", () => {
    test("getWalletProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
            options: { include_metadata: true, include_labels: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getWalletProfile({
            wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
            options: {
                include_metadata: true,
                include_labels: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getWalletProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getWalletProfile({
                wallet: "wallet",
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getWalletProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getWalletProfile({
                wallet: "wallet",
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getWalletProfile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getWalletProfile({
                wallet: "wallet",
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getWalletProfile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getWalletProfile({
                wallet: "wallet",
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getWalletProfile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getWalletProfile({
                wallet: "wallet",
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("searchWalletProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            limit: 10,
            query: { text: "cupsey", fields: ["wallet_address"] },
            sort: { field: "metrics.7d.cumulative_pnl", direction: "desc" },
            dynamic_labels: { smart: {} },
            options: { include_metadata: true, include_labels: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.searchWalletProfiles({
            limit: 10,
            query: {
                text: "cupsey",
                fields: ["wallet_address"],
            },
            sort: {
                field: "metrics.7d.cumulative_pnl",
                direction: "desc",
            },
            dynamic_labels: {
                smart: {},
            },
            options: {
                include_metadata: true,
                include_labels: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchWalletProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchWalletProfiles();
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("searchWalletProfiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchWalletProfiles();
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("searchWalletProfiles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchWalletProfiles();
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("searchWalletProfiles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchWalletProfiles();
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("searchWalletProfiles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchWalletProfiles();
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getTokenProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            options: { include_metadata: true, include_market: true, include_labels: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getTokenProfile({
            token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            options: {
                include_metadata: true,
                include_market: true,
                include_labels: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTokenProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTokenProfile({
                token: "token",
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getTokenProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTokenProfile({
                token: "token",
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getTokenProfile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTokenProfile({
                token: "token",
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getTokenProfile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTokenProfile({
                token: "token",
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getTokenProfile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTokenProfile({
                token: "token",
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("searchTokenProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            limit: 10,
            query: { text: "bonk", fields: ["metadata.name"] },
            sort: { field: "market.liquidity", direction: "desc" },
            dynamic_labels: { trending: {} },
            options: { include_metadata: true, include_market: true, include_labels: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.searchTokenProfiles({
            limit: 10,
            query: {
                text: "bonk",
                fields: ["metadata.name"],
            },
            sort: {
                field: "market.liquidity",
                direction: "desc",
            },
            dynamic_labels: {
                trending: {},
            },
            options: {
                include_metadata: true,
                include_market: true,
                include_labels: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchTokenProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchTokenProfiles();
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("searchTokenProfiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchTokenProfiles();
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("searchTokenProfiles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchTokenProfiles();
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("searchTokenProfiles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchTokenProfiles();
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("searchTokenProfiles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.searchTokenProfiles();
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getTrades (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { limit: 20, wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getTrades({
            limit: 20,
            wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTrades (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTrades();
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getTrades (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTrades();
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getTrades (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTrades();
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getTrades (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTrades();
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getTrades (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getTrades();
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getSwaps (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { limit: 20, wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK" };
        const rawResponseBody = {};

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getSwaps({
            limit: 20,
            wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getSwaps (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getSwaps();
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getSwaps (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getSwaps();
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getSwaps (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getSwaps();
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getSwaps (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getSwaps();
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getSwaps (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getSwaps();
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getPrice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"] };
        const rawResponseBody = [{}];

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getPrice({
            tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPrice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPrice({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getPrice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPrice({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getPrice (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPrice({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getPrice (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPrice({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getPrice (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPrice({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getPriceStats (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"] };
        const rawResponseBody = [{}];

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getPriceStats({
            tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceStats (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceStats({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getPriceStats (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceStats({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getPriceStats (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceStats({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getPriceStats (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceStats({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getPriceStats (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"] };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceStats({
                tokens: ["tokens", "tokens"],
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getPriceCandles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 60,
        };
        const rawResponseBody = [{}];

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getPriceCandles({
            token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 60,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceCandles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceCandles({
                token: "token",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getPriceCandles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceCandles({
                token: "token",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getPriceCandles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceCandles({
                token: "token",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getPriceCandles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceCandles({
                token: "token",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getPriceCandles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { token: "token", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceCandles({
                token: "token",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });

    test("getPriceHistory (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 3600,
        };
        const rawResponseBody = [{}];

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.solana.dex.getPriceHistory({
            tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"],
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 3600,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceHistory (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"], from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceHistory({
                tokens: ["tokens", "tokens"],
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.BadRequestError);
    });

    test("getPriceHistory (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"], from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceHistory({
                tokens: ["tokens", "tokens"],
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.UnauthorizedError);
    });

    test("getPriceHistory (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"], from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceHistory({
                tokens: ["tokens", "tokens"],
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.ForbiddenError);
    });

    test("getPriceHistory (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"], from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceHistory({
                tokens: ["tokens", "tokens"],
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.TooManyRequestsError);
    });

    test("getPriceHistory (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismApiClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { tokens: ["tokens", "tokens"], from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/solana/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.solana.dex.getPriceHistory({
                tokens: ["tokens", "tokens"],
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(PrismApi.InternalServerError);
    });
});
