// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../index.js";

export interface SubscribePayload {
    method?: SubscribePayload.Method | undefined;
    topic?: SubscribePayload.Topic | undefined;
    params?: SubscribePayload.Params | undefined;
}

export namespace SubscribePayload {
    export const Method = {
        Subscribe: "subscribe",
        Unsubscribe: "unsubscribe",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
    export const Topic = {
        SolanaDexPrices: "solana.dex.prices",
        SolanaDexSwaps: "solana.dex.swaps",
        SolanaDexTrades: "solana.dex.trades",
        SolanaDexPools: "solana.dex.pools",
        SolanaDexProfilesWallet: "solana.dex.profiles.wallet",
        SolanaDexProfilesToken: "solana.dex.profiles.token",
        SolanaDexProfilesPosition: "solana.dex.profiles.position",
        SolanaAssetsTransfers: "solana.assets.transfers",
        SolanaAssetsBalanceChanges: "solana.assets.balance-changes",
    } as const;
    export type Topic = (typeof Topic)[keyof typeof Topic];
    export type Params =
        | Prism.websocket.SubscribeSolanaDexPricesParams
        | Prism.websocket.SubscribeSolanaDexSwapsParams
        | Prism.websocket.SubscribeSolanaDexTradesParams
        | Prism.websocket.SubscribeSolanaDexPoolsParams
        | Prism.websocket.SubscribeSolanaDexWalletProfilesParams
        | Prism.websocket.SubscribeSolanaDexTokenProfilesParams
        | Prism.websocket.SubscribeSolanaDexPositionProfilesParams
        | Prism.websocket.SubscribeSolanaAssetsTransfersParams
        | Prism.websocket.SubscribeSolanaAssetsBalanceChangesParams;
}
