// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../index.js";

export interface SubscribePayload {
    method?: SubscribePayload.Method | undefined;
    topic?: SubscribePayload.Topic | undefined;
    params?: SubscribePayload.Params | undefined;
}

export namespace SubscribePayload {
    export const Method = {
        Subscribe: "subscribe",
        Unsubscribe: "unsubscribe",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
    export const Topic = {
        SolanaDexPrice: "solana.dex.price",
        SolanaDexSwapWallet: "solana.dex.swap.wallet",
        SolanaDexSwapToken: "solana.dex.swap.token",
        SolanaDexTradeWallet: "solana.dex.trade.wallet",
        SolanaDexTradeToken: "solana.dex.trade.token",
        SolanaDexProfileWallet: "solana.dex.profile.wallet",
        SolanaDexProfileToken: "solana.dex.profile.token",
        SolanaDexProfilePosition: "solana.dex.profile.position",
    } as const;
    export type Topic = (typeof Topic)[keyof typeof Topic];
    export type Params =
        | Prism.websocket.SubscribeSolanaDexPricesParams
        | Prism.websocket.SubscribeSolanaDexSwapsParams
        | Prism.websocket.SubscribeSolanaDexTradesParams
        | Prism.websocket.SubscribeSolanaDexWalletProfilesParams
        | Prism.websocket.SubscribeSolanaDexTokenProfilesParams
        | Prism.websocket.SubscribeSolanaDexPositionProfilesParams;
}
