// This file was auto-generated by Fern from our API Definition.

export interface EvmDexPriceCandle {
    timestamp?: string | undefined;
    open?: number | undefined;
    high?: number | undefined;
    low?: number | undefined;
    close?: number | undefined;
    volume?: number | undefined;
    count?: number | undefined;
}
