// This file was auto-generated by Fern from our API Definition.

export const EvmDexPositionProfileTimeWindowEnum = {
    Window30D: "30d",
    Window14D: "14d",
    Window7D: "7d",
    Window3D: "3d",
    Window1D: "1d",
} as const;
export type EvmDexPositionProfileTimeWindowEnum =
    (typeof EvmDexPositionProfileTimeWindowEnum)[keyof typeof EvmDexPositionProfileTimeWindowEnum];
