// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

/**
 * Conditions that a profile must satisfy to be included in the results.
 * Each key is either a field path paired with comparison operators, or a logical operator (`$and`, `$or`) that combines nested filter objects.
 */
export interface EvmDexProfileSearchPayloadFilter {
    /** Logical AND. A profile must satisfy every nested filter to match. */
    $and?: Prism.api.EvmDexProfileSearchPayloadFilter[] | undefined;
    /** Logical OR. A profile must satisfy at least one nested filter to match. */
    $or?: Prism.api.EvmDexProfileSearchPayloadFilter[] | undefined;
}
