// This file was auto-generated by Fern from our API Definition.

export const EvmDexTradePositionStateEnum = {
    Open: "open",
    Close: "close",
    Trade: "trade",
    Unknown: "unknown",
} as const;
export type EvmDexTradePositionStateEnum =
    (typeof EvmDexTradePositionStateEnum)[keyof typeof EvmDexTradePositionStateEnum];
