// This file was auto-generated by Fern from our API Definition.

/** Direction to sort results in. */
export const EvmDexProfileSearchPayloadSortDirectionEnum = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type EvmDexProfileSearchPayloadSortDirectionEnum =
    (typeof EvmDexProfileSearchPayloadSortDirectionEnum)[keyof typeof EvmDexProfileSearchPayloadSortDirectionEnum];
