// This file was auto-generated by Fern from our API Definition.

export const EvmDexSwapTypeEnum = {
    QuoteToken: "quote_token",
    TokenQuote: "token_quote",
    TokenToken: "token_token",
    QuoteQuote: "quote_quote",
} as const;
export type EvmDexSwapTypeEnum = (typeof EvmDexSwapTypeEnum)[keyof typeof EvmDexSwapTypeEnum];
