// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface EvmDexSwap {
    id?: number | undefined;
    /** Numeric EVM chain ID the record belongs to. */
    chain_id?: number | undefined;
    swap_type?: Prism.api.EvmDexSwapTypeEnum | undefined;
    protocol?: Prism.api.EvmDexProtocolField | undefined;
    wallet_address?: string | undefined;
    pool_address?: string | undefined;
    token_address_in?: string | undefined;
    token_address_out?: string | undefined;
    token_amount_in?: number | undefined;
    token_amount_out?: number | undefined;
    token_price_in?: number | undefined;
    token_price_out?: number | undefined;
    pre_token_balance_in?: number | undefined;
    pre_token_balance_out?: number | undefined;
    post_token_balance_in?: number | undefined;
    post_token_balance_out?: number | undefined;
    usd_amount_in?: number | undefined;
    usd_amount_out?: number | undefined;
    block_number?: number | undefined;
    block_time?: string | undefined;
    tx_hash?: string | undefined;
}
