// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface EvmDexWalletProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    /** Numeric EVM chain ID the record belongs to. */
    chain_id?: number | undefined;
    wallet_address?: string | undefined;
    metadata?: Prism.api.EvmDexWalletProfileMetadata | undefined;
    metrics?: Record<string, Prism.api.EvmDexWalletProfileMetrics> | undefined;
}
