// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface EvmDexWalletProfileSearchPayloadQuery {
    /** Wallet profile fields that the text value should be matched against. */
    fields?: Prism.api.EvmDexWalletProfileSearchPayloadQueryTargetsEnum[] | undefined;
    /** Text value to match against the selected fields. */
    text: string;
    /** When true, matches values that are approximately similar to `text`, allowing for minor typos and variations. */
    fuzzy?: boolean | undefined;
    /** When true, matches values that start with `text`, useful for type-ahead lookups. */
    autocomplete?: boolean | undefined;
}
