// This file was auto-generated by Fern from our API Definition.

export const EvmDexTokenProfileTimeWindowEnum = {
    Window7D: "7d",
    Window1D: "1d",
    Window6H: "6h",
    Window1H: "1h",
    Window5M: "5m",
    Window1M: "1m",
} as const;
export type EvmDexTokenProfileTimeWindowEnum =
    (typeof EvmDexTokenProfileTimeWindowEnum)[keyof typeof EvmDexTokenProfileTimeWindowEnum];
