// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface EvmDexTokenProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    /** Numeric EVM chain ID the record belongs to. */
    chain_id?: number | undefined;
    token_address?: string | undefined;
    metadata?: Prism.api.EvmDexTokenProfileMetadata | undefined;
    metrics?: Record<string, Prism.api.EvmDexTokenProfileMetrics> | undefined;
}
