// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

/**
 * Controls which optional sections are included in each returned token profile.
 */
export interface EvmDexTokenProfilePayloadOptions {
    /** When true, includes the `metadata` object in each returned profile. */
    include_metadata?: boolean | undefined;
    /** Time windows for which metrics should be included. Windows not listed are omitted from the response. */
    include_metrics?: Prism.api.EvmDexTokenProfileTimeWindowEnum[] | undefined;
}
