// This file was auto-generated by Fern from our API Definition.

export const EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum = {
    TokenAddress: "token_address",
} as const;
export type EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum =
    (typeof EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum)[keyof typeof EvmDexTokenProfileSearchPayloadQueryFieldTargetsEnum];
