// This file was auto-generated by Fern from our API Definition.

export const EvmDexTradeDirectionEnum = {
    Buy: "buy",
    Sell: "sell",
} as const;
export type EvmDexTradeDirectionEnum = (typeof EvmDexTradeDirectionEnum)[keyof typeof EvmDexTradeDirectionEnum];
