// This file was auto-generated by Fern from our API Definition.

export const EvmDexWalletProfileSearchPayloadQueryTargetsEnum = {
    WalletAddress: "wallet_address",
} as const;
export type EvmDexWalletProfileSearchPayloadQueryTargetsEnum =
    (typeof EvmDexWalletProfileSearchPayloadQueryTargetsEnum)[keyof typeof EvmDexWalletProfileSearchPayloadQueryTargetsEnum];
