// This file was auto-generated by Fern from our API Definition.

export interface PaginatedResponse {
    /** Total number of matching items */
    count?: number | undefined;
    /** Cursor for pagination */
    cursor?: string | undefined;
}
