// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface SolanaDexWalletProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    wallet_address?: string | undefined;
    labels?: Prism.api.SolanaDexWalletProfileLabels | undefined;
    matched_labels?: Record<string, string[]> | undefined;
    dynamic_labels?: Prism.api.SolanaDexProfileDynamicLabels | undefined;
    metadata?: Prism.api.SolanaDexWalletProfileMetadata | undefined;
    identity?: Prism.api.SolanaDexWalletProfileIdentity | undefined;
    metrics?: Record<string, Prism.api.SolanaDexWalletProfileMetrics> | undefined;
}
