// This file was auto-generated by Fern from our API Definition.

export const SolanaDexTradePositionStateEnum = {
    Open: "open",
    Close: "close",
    Trade: "trade",
} as const;
export type SolanaDexTradePositionStateEnum =
    (typeof SolanaDexTradePositionStateEnum)[keyof typeof SolanaDexTradePositionStateEnum];
