// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../index.js";

export interface SolanaDexPositionProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    position_address?: string | undefined;
    wallet_address?: string | undefined;
    token_address?: string | undefined;
    labels?: Prism.api.SolanaDexPositionProfileLabels | undefined;
    dynamic_labels?: Prism.api.SolanaDexProfileDynamicLabels | undefined;
    metadata?: Prism.api.SolanaDexPositionProfileMetadata | undefined;
    metrics?: Record<string, Prism.api.SolanaDexPositionProfileMetrics> | undefined;
}
