// This file was auto-generated by Fern from our API Definition.

/**
 * Comparison operators applied to a single field. At least one operator must be provided.
 */
export interface SolanaDexProfileSearchPayloadFilterOperators {
    /** Equal to. */
    $eq?: SolanaDexProfileSearchPayloadFilterOperators.Eq | undefined;
    /** Not equal to. */
    $ne?: SolanaDexProfileSearchPayloadFilterOperators.Ne | undefined;
    /** Greater than. */
    $gt?: number | undefined;
    /** Less than. */
    $lt?: number | undefined;
    /** Greater than or equal to. */
    $gte?: number | undefined;
    /** Less than or equal to. */
    $lte?: number | undefined;
    /** In the list. */
    $in?: SolanaDexProfileSearchPayloadFilterOperators.In.Item[] | undefined;
    /** Not in the list. */
    $nin?: SolanaDexProfileSearchPayloadFilterOperators.Nin.Item[] | undefined;
}

export namespace SolanaDexProfileSearchPayloadFilterOperators {
    /**
     * Equal to.
     */
    export type Eq = string | number | boolean;
    /**
     * Not equal to.
     */
    export type Ne = string | number | boolean;
    export type In = In.Item[];

    export namespace In {
        export type Item = string | number;
    }

    export type Nin = Nin.Item[];

    export namespace Nin {
        export type Item = string | number;
    }
}
