// This file was auto-generated by Fern from our API Definition.

export interface SolanaDexWalletProfileIdentity {
    name?: string | undefined;
    twitter_username?: string | undefined;
    telegram_username?: string | undefined;
}
