// This file was auto-generated by Fern from our API Definition.

export interface SolanaDexTokenProfileMetadata {
    last_trade_at?: string | undefined;
    created_at?: string | undefined;
    symbol?: string | undefined;
    name?: string | undefined;
    image?: string | undefined;
    verified?: boolean | undefined;
    creator_address?: string | undefined;
    twitter?: string | undefined;
    discord?: string | undefined;
    website?: string | undefined;
    telegram?: string | undefined;
}
