// This file was auto-generated by Fern from our API Definition.

export const SolanaDexWalletProfileLabelEnum = {
    Kol: "kol",
    Trencher: "trencher",
    Conviction: "conviction",
    Smart: "smart",
    Whale: "whale",
    Degen: "degen",
    Sniper: "sniper",
    Swing: "swing",
    Holder: "holder",
} as const;
export type SolanaDexWalletProfileLabelEnum =
    (typeof SolanaDexWalletProfileLabelEnum)[keyof typeof SolanaDexWalletProfileLabelEnum];
