// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         tokens: ["Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk"]
 *     }
 */
export interface GetPriceDexRequest {
    /** Token addresses to retrieve the latest prices for. */
    tokens?: string[];
    /** Pool addresses to retrieve the latest prices for. */
    pools?: string[];
}
