// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "Z4d9YXR4pSkdKcu9UBcwxHp7i32buzdDtAR1b1Gbonk",
 *         from: "2026-04-27T00:00:00Z",
 *         to: "2026-04-27T01:00:00Z",
 *         interval: 60
 *     }
 */
export interface GetPriceCandlesDexRequest {
    /** Token address to retrieve price candles for. */
    token: string;
    /**
     * Start of the candle range, as a date-time RFC3339 string.
     * Must be combined with `to` to define a bounded range.
     */
    from?: string;
    /**
     * End of the candle range, as a date-time RFC3339 string. Defaults to the current time.
     * Must be combined with either `from` (to define a bounded range) or `count` (to return the N most recent candles ending at `to`).
     */
    to?: string;
    /**
     * Number of candles to return, ending at `to`.
     * Must be combined with `to`.
     */
    count?: number;
    /** Sampling interval between data points, in seconds. */
    interval: number;
}
