// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20
 *     }
 */
export interface GetSwapsDexRequest extends Prism.api.PayloadPagination {
    /** Wallet address to filter swaps by. When combined with `token`, returns only swaps for that wallet on that token. */
    wallet_address?: string;
    /** Token address to filter swaps by. When combined with `wallet`, returns only swaps for that wallet on that token. */
    token_address?: string;
}
