// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"
 *     }
 */
export interface GetSwapsDexRequest extends Prism.api.PayloadPagination {
    /** Wallet address to filter swaps by. */
    wallet?: string;
    /** Token address to filter swaps by. */
    token?: string;
    /** Pool address to filter swaps by. */
    pool?: string;
}
