// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         options: {
 *             include_metadata: true,
 *             include_market: true,
 *             include_labels: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface GetTokenProfileDexRequest {
    /** Token address to retrieve the profile for. */
    token_address?: string;
    options?: Prism.api.SolanaDexTokenProfilePayloadOptions;
}
