// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 20,
 *         wallet: "suqh5sHtr8HyJ7q8scBimULPkPpA557prMG47xCHQfK"
 *     }
 */
export interface GetTradesDexRequest extends Prism.api.PayloadPagination {
    /** Wallet address to filter trades by. */
    wallet?: string;
    /** Token address to filter trades by. */
    token?: string;
}
