// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         options: {
 *             include_metadata: true,
 *             include_labels: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface GetWalletProfileDexRequest {
    /** Wallet address to retrieve the profile for. */
    wallet_address?: string;
    options?: Prism.api.SolanaDexWalletProfilePayloadOptions;
}
