// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         sort: {
 *             field: "metrics.7d.pnl",
 *             direction: "desc"
 *         },
 *         dynamic_labels: {
 *             "winner": {}
 *         },
 *         options: {
 *             include_metadata: true,
 *             include_labels: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface SearchPositionProfilesDexRequest extends Prism.api.PayloadPagination {
    filter?: Prism.api.SolanaDexProfileSearchPayloadFilter;
    sort?: Prism.api.SolanaDexProfileSearchPayloadSort;
    dynamic_labels?: Prism.api.SolanaDexProfileSearchPayloadDynamicLabels;
    options?: Prism.api.SolanaDexPositionProfilePayloadOptions;
}
