// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         query: {
 *             text: "cupsey",
 *             fields: ["identity.name"]
 *         },
 *         sort: {
 *             field: "metrics.7d.cumulative_pnl",
 *             direction: "desc"
 *         },
 *         dynamic_labels: {
 *             "smart": {}
 *         },
 *         options: {
 *             include_metadata: true,
 *             include_labels: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface SearchWalletProfilesDexRequest extends Prism.api.PayloadPagination {
    query?: Prism.api.SolanaDexWalletProfileSearchPayloadQuery;
    filter?: Prism.api.SolanaDexProfileSearchPayloadFilter;
    sort?: Prism.api.SolanaDexProfileSearchPayloadSort;
    dynamic_labels?: Prism.api.SolanaDexProfileSearchPayloadDynamicLabels;
    options?: Prism.api.SolanaDexWalletProfilePayloadOptions;
}
