// This file was auto-generated by Fern from our API Definition.

export interface SubscribeWalletSwaps {
    method: string;
    topic: string;
    params: SubscribeWalletSwaps.Params;
}

export namespace SubscribeWalletSwaps {
    export interface Params {
        wallets?: string[] | undefined;
    }
}
