// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../index.js";

export interface SearchPositionProfilesDexResponse extends Prism.api.PaginatedResponse {
    data?: Prism.api.SolanaDexPositionProfile[] | undefined;
}
