// This file was auto-generated by Fern from our API Definition.

import type * as Prism from "../../../../../../../index.js";

export interface SearchWalletProfilesDexResponse extends Prism.api.PaginatedResponse {
    data?: Prism.api.SolanaDexWalletProfile[] | undefined;
}
