// This file was auto-generated by Fern from our API Definition.

export interface PricesSubscriptionMessage {
    topic?: string | undefined;
    data?: PricesSubscriptionMessage.Data | undefined;
}

export namespace PricesSubscriptionMessage {
    export interface Data {
        token_address?: string | undefined;
        usd_price?: number | undefined;
        block_slot?: number | undefined;
        block_time?: string | undefined;
    }
}
