// This file was auto-generated by Fern from our API Definition.

export interface SubscribePrices {
    method: string;
    topic: string;
    params: SubscribePrices.Params;
}

export namespace SubscribePrices {
    export interface Params {
        tokens?: string[] | undefined;
    }
}
