// This file was auto-generated by Fern from our API Definition.

export interface PayloadPagination {
    /** Maximum number of results to return in a single page. */
    limit?: number | undefined;
    /** Opaque cursor returned by a previous response. Pass it to fetch the next page of results. */
    cursor?: string | undefined;
}
