// This file was auto-generated by Fern from our API Definition.

import type * as ApiClient from "../index.js";

export interface SolanaDexWalletProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    wallet_address?: string | undefined;
    labels?: ApiClient.SolanaDexWalletProfileLabels | undefined;
    matched_labels?: Record<string, string[]> | undefined;
    dynamic_labels?: ApiClient.SolanaDexProfileDynamicLabels | undefined;
    metadata?: ApiClient.SolanaDexWalletProfileMetadata | undefined;
    identity?: ApiClient.SolanaDexWalletProfileIdentity | undefined;
    metrics?: Record<string, ApiClient.SolanaDexWalletProfileMetrics> | undefined;
}
