// This file was auto-generated by Fern from our API Definition.

import type * as ApiClient from "../index.js";

export interface SolanaDexTokenProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    token_address?: string | undefined;
    labels?: ApiClient.SolanaDexTokenProfileLabels | undefined;
    matched_labels?: Record<string, string[]> | undefined;
    dynamic_labels?: ApiClient.SolanaDexProfileDynamicLabels | undefined;
    metadata?: ApiClient.SolanaDexTokenProfileMetadata | undefined;
    market?: ApiClient.SolanaDexTokenProfileMarket | undefined;
    metrics?: Record<string, ApiClient.SolanaDexTokenProfileMetrics> | undefined;
}
