// This file was auto-generated by Fern from our API Definition.

import type * as ApiClient from "../index.js";

export type SolanaDexTokenProfileLabels = ApiClient.SolanaDexTokenProfileLabelEnum[];
