// This file was auto-generated by Fern from our API Definition.

/** Direction to sort results in. */
export const SolanaDexProfileSearchPayloadSortDirectionEnum = {
    Asc: "asc",
    Desc: "desc",
} as const;
export type SolanaDexProfileSearchPayloadSortDirectionEnum =
    (typeof SolanaDexProfileSearchPayloadSortDirectionEnum)[keyof typeof SolanaDexProfileSearchPayloadSortDirectionEnum];
