// This file was auto-generated by Fern from our API Definition.

/**
 * Full-text query used to match profiles by a text value against one or more fields.
 */
export interface SolanaDexProfileSearchPayloadQuery {
    /** Text value to match against the selected fields. */
    text: string;
    /** Fields that the text value should be matched against. */
    fields: string[];
    /** When true, matches values that are approximately similar to `text`, allowing for minor typos and variations. */
    fuzzy?: boolean | undefined;
    /** When true, matches values that start with `text`, useful for type-ahead lookups. */
    autocomplete?: boolean | undefined;
}
