// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../index.js";

export interface SolanaDexWalletProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    wallet_address?: string | undefined;
    labels?: PrismApi.SolanaDexWalletProfileLabels | undefined;
    matched_labels?: Record<string, string[]> | undefined;
    dynamic_labels?: PrismApi.SolanaDexProfileDynamicLabels | undefined;
    metadata?: PrismApi.SolanaDexWalletProfileMetadata | undefined;
    identity?: PrismApi.SolanaDexWalletProfileIdentity | undefined;
    metrics?: Record<string, PrismApi.SolanaDexWalletProfileMetrics> | undefined;
}
