// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../index.js";

export interface SolanaDexTrade {
    protocol?: PrismApi.SolanaDexProtocolField | undefined;
    swap_type?: PrismApi.SolanaDexSwapTypeEnum | undefined;
    wallet_address?: string | undefined;
    token_address?: string | undefined;
    quote_address?: string | undefined;
    position_address?: string | undefined;
    direction?: PrismApi.SolanaDexTradeDirectionEnum | undefined;
    position_state?: PrismApi.SolanaDexTradePositionStateEnum | undefined;
    token_amount?: number | undefined;
    quote_amount?: number | undefined;
    native_amount?: number | undefined;
    usd_amount?: number | undefined;
    pre_token_balance?: number | undefined;
    post_token_balance?: number | undefined;
    token_price?: number | undefined;
    quote_price?: number | undefined;
    token_mcap?: number | undefined;
    block_slot?: number | undefined;
    block_time?: number | undefined;
    tx_hash?: string | undefined;
}
