// This file was auto-generated by Fern from our API Definition.

export const SolanaDexWalletProfileSearchPayloadQueryTargetsEnum = {
    WalletAddress: "wallet_address",
    IdentityName: "identity.name",
    IdentityTwitterUsername: "identity.twitter_username",
    IdentityTelegramUsername: "identity.telegram_username",
} as const;
export type SolanaDexWalletProfileSearchPayloadQueryTargetsEnum =
    (typeof SolanaDexWalletProfileSearchPayloadQueryTargetsEnum)[keyof typeof SolanaDexWalletProfileSearchPayloadQueryTargetsEnum];
