// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../index.js";

export interface SolanaDexTokenProfile {
    updated_at?: string | undefined;
    synced_at?: string | undefined;
    token_address?: string | undefined;
    labels?: PrismApi.SolanaDexTokenProfileLabels | undefined;
    matched_labels?: Record<string, string[]> | undefined;
    dynamic_labels?: PrismApi.SolanaDexProfileDynamicLabels | undefined;
    metadata?: PrismApi.SolanaDexTokenProfileMetadata | undefined;
    market?: PrismApi.SolanaDexTokenProfileMarket | undefined;
    metrics?: Record<string, PrismApi.SolanaDexTokenProfileMetrics> | undefined;
}
