// This file was auto-generated by Fern from our API Definition.

import type * as PrismApi from "../index.js";

/**
 * Controls which optional sections are included in each returned token profile.
 */
export interface SolanaDexTokenProfilePayloadOptions {
    /** When true, includes the `metadata` object in each returned profile. */
    include_metadata?: boolean | undefined;
    /** When true, includes the `market` object (price, liquidity, supply) in each returned profile. */
    include_market?: boolean | undefined;
    /** When true, includes the `labels` array in each returned profile. */
    include_labels?: boolean | undefined;
    /** Time windows for which metrics should be included. Windows not listed are omitted from the response. */
    include_metrics?: PrismApi.SolanaDexTokenProfileTimeWindowEnum[] | undefined;
}
