// This file was auto-generated by Fern from our API Definition.

import * as Prism from "../../../../src/api/index";
import { PrismClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";

describe("DexClient", () => {
    test("getWalletProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            updated_at: "2024-01-15T09:30:00Z",
            synced_at: "2024-01-15T09:30:00Z",
            chain_id: 1,
            wallet_address: "wallet_address",
            metadata: { last_trade_at: "2024-01-15T09:30:00Z" },
            metrics: {
                key: {
                    risk_score: 1.1,
                    consistency_score: 1.1,
                    largest_win: 1.1,
                    largest_loss: 1.1,
                    max_consecutive_wins: 1,
                    max_consecutive_losses: 1,
                    avg_buy_size: 1.1,
                    avg_sell_size: 1.1,
                    avg_buy_mcap: 1.1,
                    avg_sell_mcap: 1.1,
                    avg_daily_pnl: 1.1,
                    avg_daily_roi: 1.1,
                    avg_daily_trade_count: 1,
                    avg_daily_traded_tokens: 1,
                    avg_daily_volume: 1.1,
                    avg_holding_duration: 1,
                    avg_trade_delta: 1,
                    avg_pnl: 1.1,
                    avg_roi: 1.1,
                    avg_token_pnl: 1.1,
                    avg_token_roi: 1.1,
                    token_roi_distribution: { key: 1 },
                    trade_count: 1,
                    buy_count: 1,
                    sell_count: 1,
                    position_count: 1,
                    win_count: 1,
                    loss_count: 1,
                    pnl: 1.1,
                    win_pnl: 1.1,
                    loss_pnl: 1.1,
                    volume: 1.1,
                    buy_volume: 1.1,
                    sell_volume: 1.1,
                    winrate: 1.1,
                    volume_weighted_winrate: 1.1,
                    roi: 1.1,
                    volume_weighted_roi: 1.1,
                    time_weighted_roi: 1.1,
                    pnl_volume_ratio: 1.1,
                    token_hit_ratio: 1.1,
                    win_loss_size_ratio: 1.1,
                    profit_factor: 1.1,
                    profit_expectancy: 1.1,
                    recovery_factor: 1.1,
                    winrate_stability: 1.1,
                    winrate_volatility: 1.1,
                    pnl_stability: 1.1,
                    pnl_volatility: 1.1,
                    roi_stability: 1.1,
                    roi_volatility: 1.1,
                    sharpe_ratio: 1.1,
                    sortino_ratio: 1.1,
                    max_drawdown: 1.1,
                    risk_of_ruin: 1.1,
                    turnover: 1.1,
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getWalletProfile({
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getWalletProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getWalletProfile({
                chain_id: 1,
                wallet: "wallet",
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getWalletProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getWalletProfile({
                chain_id: 1,
                wallet: "wallet",
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getWalletProfile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getWalletProfile({
                chain_id: 1,
                wallet: "wallet",
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getWalletProfile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getWalletProfile({
                chain_id: 1,
                wallet: "wallet",
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getWalletProfile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getWalletProfile({
                chain_id: 1,
                wallet: "wallet",
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("searchWalletProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            limit: 10,
            chain_id: 1,
            query: { text: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045", fields: ["wallet_address"] },
            sort: { field: "metrics.7d.cumulative_pnl", direction: "desc" },
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            count: 1,
            cursor: "cursor",
            data: [
                {
                    updated_at: "2024-01-15T09:30:00Z",
                    synced_at: "2024-01-15T09:30:00Z",
                    chain_id: 1,
                    wallet_address: "wallet_address",
                    metrics: { key: {} },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.searchWalletProfiles({
            limit: 10,
            chain_id: 1,
            query: {
                text: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                fields: ["wallet_address"],
            },
            sort: {
                field: "metrics.7d.cumulative_pnl",
                direction: "desc",
            },
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchWalletProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchWalletProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("searchWalletProfiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchWalletProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("searchWalletProfiles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchWalletProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("searchWalletProfiles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchWalletProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("searchWalletProfiles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/wallets/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchWalletProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getTokenProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            chain_id: 1,
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            updated_at: "2024-01-15T09:30:00Z",
            synced_at: "2024-01-15T09:30:00Z",
            chain_id: 1,
            token_address: "token_address",
            metadata: {
                last_trade_at: "2024-01-15T09:30:00Z",
                created_at: "2024-01-15T09:30:00Z",
                symbol: "symbol",
                name: "name",
                image: "image",
                verified: true,
                creator_address: "creator_address",
                twitter: "twitter",
                discord: "discord",
                website: "website",
                telegram: "telegram",
            },
            metrics: {
                key: {
                    largest_trade_win: 1.1,
                    largest_trade_loss: 1.1,
                    avg_buy_size: 1.1,
                    avg_sell_size: 1.1,
                    avg_price: 1.1,
                    avg_buy_price: 1.1,
                    avg_sell_price: 1.1,
                    avg_buy_mcap: 1.1,
                    avg_sell_mcap: 1.1,
                    avg_holding_duration: 1,
                    avg_trade_pnl: 1.1,
                    avg_trade_roi: 1.1,
                    avg_wallet_winrate: 1.1,
                    avg_wallet_pnl: 1.1,
                    avg_wallet_roi: 1.1,
                    wallet_roi_distribution: { key: 1 },
                    makers_count: 1,
                    buyers_count: 1,
                    sellers_count: 1,
                    buy_count: 1,
                    sell_count: 1,
                    win_position_count: 1,
                    loss_position_count: 1,
                    win_pnl: 1.1,
                    loss_pnl: 1.1,
                    buy_volume: 1.1,
                    sell_volume: 1.1,
                    pnl: 1.1,
                    trade_count: 1,
                    volume: 1.1,
                    position_count: 1,
                    volume_weighted_winrate: 1.1,
                    volume_weighted_roi: 1.1,
                    wallet_hit_ratio: 1.1,
                    profit_factor: 1.1,
                    win_loss_size_ratio: 1.1,
                    pnl_volume_ratio: 1.1,
                    price_stability: 1.1,
                    price_volatility: 1.1,
                    roi_stability: 1.1,
                    roi_volatility: 1.1,
                    pnl_volatility: 1.1,
                    pnl_stability: 1.1,
                    sharpe_ratio: 1.1,
                    sortino_ratio: 1.1,
                    max_drawdown: 1.1,
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getTokenProfile({
            chain_id: 1,
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTokenProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTokenProfile({
                chain_id: 1,
                token: "token",
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getTokenProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTokenProfile({
                chain_id: 1,
                token: "token",
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getTokenProfile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTokenProfile({
                chain_id: 1,
                token: "token",
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getTokenProfile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTokenProfile({
                chain_id: 1,
                token: "token",
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getTokenProfile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTokenProfile({
                chain_id: 1,
                token: "token",
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("searchTokenProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            limit: 10,
            chain_id: 1,
            query: { text: "0x6982508145454Ce325dDbE47a25d4ec3d2311933", fields: ["token_address"] },
            sort: { field: "metrics.1d.usd_volume", direction: "desc" },
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            count: 1,
            cursor: "cursor",
            data: [
                {
                    updated_at: "2024-01-15T09:30:00Z",
                    synced_at: "2024-01-15T09:30:00Z",
                    chain_id: 1,
                    token_address: "token_address",
                    metrics: { key: {} },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.searchTokenProfiles({
            limit: 10,
            chain_id: 1,
            query: {
                text: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
                fields: ["token_address"],
            },
            sort: {
                field: "metrics.1d.usd_volume",
                direction: "desc",
            },
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchTokenProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchTokenProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("searchTokenProfiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchTokenProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("searchTokenProfiles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchTokenProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("searchTokenProfiles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchTokenProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("searchTokenProfiles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/tokens/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchTokenProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getPositionProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            updated_at: "2024-01-15T09:30:00Z",
            synced_at: "2024-01-15T09:30:00Z",
            chain_id: 1,
            position_address: "position_address",
            wallet_address: "wallet_address",
            token_address: "token_address",
            metadata: { last_trade_at: "2024-01-15T09:30:00Z" },
            metrics: {
                key: {
                    risk_score: 1.1,
                    consistency_score: 1.1,
                    largest_win: 1.1,
                    largest_loss: 1.1,
                    max_consecutive_wins: 1,
                    max_consecutive_losses: 1,
                    avg_buy_size: 1.1,
                    avg_sell_size: 1.1,
                    avg_buy_mcap: 1.1,
                    avg_sell_mcap: 1.1,
                    avg_daily_trade_count: 1,
                    avg_daily_volume: 1.1,
                    avg_daily_pnl: 1.1,
                    avg_daily_roi: 1.1,
                    avg_holding_duration: 1,
                    avg_trade_delta: 1,
                    avg_pnl: 1.1,
                    avg_roi: 1.1,
                    trade_count: 1,
                    buy_count: 1,
                    sell_count: 1,
                    win_count: 1,
                    loss_count: 1,
                    pnl: 1.1,
                    win_pnl: 1.1,
                    loss_pnl: 1.1,
                    volume: 1.1,
                    buy_volume: 1.1,
                    sell_volume: 1.1,
                    winrate: 1.1,
                    volume_weighted_winrate: 1.1,
                    roi: 1.1,
                    volume_weighted_roi: 1.1,
                    pnl_volume_ratio: 1.1,
                    win_loss_size_ratio: 1.1,
                    profit_factor: 1.1,
                    profit_expectancy: 1.1,
                    recovery_factor: 1.1,
                    winrate_stability: 1.1,
                    winrate_volatility: 1.1,
                    roi_stability: 1.1,
                    roi_volatility: 1.1,
                    pnl_stability: 1.1,
                    pnl_volatility: 1.1,
                    sharpe_ratio: 1.1,
                    sortino_ratio: 1.1,
                    max_drawdown: 1.1,
                    risk_of_ruin: 1.1,
                    turnover: 1.1,
                },
            },
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getPositionProfile({
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPositionProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet", token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPositionProfile({
                chain_id: 1,
                wallet: "wallet",
                token: "token",
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getPositionProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet", token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPositionProfile({
                chain_id: 1,
                wallet: "wallet",
                token: "token",
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getPositionProfile (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet", token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPositionProfile({
                chain_id: 1,
                wallet: "wallet",
                token: "token",
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getPositionProfile (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet", token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPositionProfile({
                chain_id: 1,
                wallet: "wallet",
                token: "token",
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getPositionProfile (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, wallet: "wallet", token: "token" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/get-profile")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPositionProfile({
                chain_id: 1,
                wallet: "wallet",
                token: "token",
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("searchPositionProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            limit: 10,
            chain_id: 1,
            sort: { field: "metrics.7d.pnl", direction: "desc" },
            options: { include_metadata: true, include_metrics: ["7d"] },
        };
        const rawResponseBody = {
            count: 1,
            cursor: "cursor",
            data: [
                {
                    updated_at: "2024-01-15T09:30:00Z",
                    synced_at: "2024-01-15T09:30:00Z",
                    chain_id: 1,
                    position_address: "position_address",
                    wallet_address: "wallet_address",
                    token_address: "token_address",
                    metrics: { key: {} },
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.searchPositionProfiles({
            limit: 10,
            chain_id: 1,
            sort: {
                field: "metrics.7d.pnl",
                direction: "desc",
            },
            options: {
                include_metadata: true,
                include_metrics: ["7d"],
            },
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("searchPositionProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchPositionProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("searchPositionProfiles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchPositionProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("searchPositionProfiles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchPositionProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("searchPositionProfiles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchPositionProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("searchPositionProfiles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/profiles/positions/search-profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.searchPositionProfiles({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getTrades (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { limit: 20, chain_id: 1, wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" };
        const rawResponseBody = {
            count: 1,
            cursor: "cursor",
            data: [
                {
                    id: 1,
                    chain_id: 1,
                    protocol: "protocol",
                    swap_type: "quote_token",
                    wallet_address: "wallet_address",
                    token_address: "token_address",
                    quote_address: "quote_address",
                    position_address: "position_address",
                    direction: "buy",
                    position_state: "open",
                    token_amount: 1.1,
                    quote_amount: 1.1,
                    native_amount: 1.1,
                    usd_amount: 1.1,
                    pre_token_balance: 1.1,
                    post_token_balance: 1.1,
                    token_price: 1.1,
                    quote_price: 1.1,
                    token_mcap: 1.1,
                    block_number: 1,
                    block_time: "2024-01-15T09:30:00Z",
                    tx_hash: "tx_hash",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getTrades({
            limit: 20,
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getTrades (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTrades({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getTrades (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTrades({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getTrades (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTrades({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getTrades (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTrades({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getTrades (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/trades/get-trades")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getTrades({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getSwaps (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { limit: 20, chain_id: 1, wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045" };
        const rawResponseBody = {
            count: 1,
            cursor: "cursor",
            data: [
                {
                    id: 1,
                    chain_id: 1,
                    swap_type: "quote_token",
                    protocol: "protocol",
                    wallet_address: "wallet_address",
                    pool_address: "pool_address",
                    token_address_in: "token_address_in",
                    token_address_out: "token_address_out",
                    token_amount_in: 1.1,
                    token_amount_out: 1.1,
                    token_price_in: 1.1,
                    token_price_out: 1.1,
                    pre_token_balance_in: 1.1,
                    pre_token_balance_out: 1.1,
                    post_token_balance_in: 1.1,
                    post_token_balance_out: 1.1,
                    usd_amount_in: 1.1,
                    usd_amount_out: 1.1,
                    block_number: 1,
                    block_time: "2024-01-15T09:30:00Z",
                    tx_hash: "tx_hash",
                },
            ],
        };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getSwaps({
            limit: 20,
            chain_id: 1,
            wallet: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getSwaps (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getSwaps({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getSwaps (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getSwaps({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getSwaps (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getSwaps({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getSwaps (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getSwaps({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getSwaps (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/swaps/get-swaps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getSwaps({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getPrice (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"] };
        const rawResponseBody = [
            {
                chain_id: 1,
                token_address: "token_address",
                pool_address: "pool_address",
                usd_price: 1.1,
                block_number: 1,
                block_time: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getPrice({
            chain_id: 1,
            tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPrice (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPrice({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getPrice (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPrice({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getPrice (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPrice({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getPrice (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPrice({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getPrice (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPrice({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getPriceStats (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"] };
        const rawResponseBody = [
            {
                token_address: "token_address",
                pool_address: "pool_address",
                usd_price: 1.1,
                usd_price_change_5m: 1.1,
                usd_price_change_1h: 1.1,
                usd_price_change_6h: 1.1,
                usd_price_change_12h: 1.1,
                usd_price_change_1d: 1.1,
                usd_price_change_7d: 1.1,
                usd_price_change_30d: 1.1,
                usd_volume_5m: 1.1,
                usd_volume_1h: 1.1,
                usd_volume_6h: 1.1,
                usd_volume_12h: 1.1,
                usd_volume_1d: 1.1,
                usd_volume_7d: 1.1,
                usd_volume_30d: 1.1,
                usd_volume_change_5m: 1.1,
                usd_volume_change_1h: 1.1,
                usd_volume_change_6h: 1.1,
                usd_volume_change_12h: 1.1,
                usd_volume_change_1d: 1.1,
                usd_volume_change_7d: 1.1,
                usd_volume_change_30d: 1.1,
                block_number: 1,
                block_time: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getPriceStats({
            chain_id: 1,
            tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceStats (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceStats({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getPriceStats (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceStats({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getPriceStats (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceStats({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getPriceStats (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceStats({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getPriceStats (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-stats")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceStats({
                chain_id: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getPriceCandles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            chain_id: 1,
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 60,
        };
        const rawResponseBody = [
            { timestamp: "2024-01-15T09:30:00Z", open: 1.1, high: 1.1, low: 1.1, close: 1.1, volume: 1.1, count: 1 },
        ];

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getPriceCandles({
            chain_id: 1,
            token: "0x6982508145454Ce325dDbE47a25d4ec3d2311933",
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 60,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceCandles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceCandles({
                chain_id: 1,
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getPriceCandles (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceCandles({
                chain_id: 1,
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getPriceCandles (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceCandles({
                chain_id: 1,
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getPriceCandles (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceCandles({
                chain_id: 1,
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getPriceCandles (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-candles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceCandles({
                chain_id: 1,
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });

    test("getPriceHistory (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {
            chain_id: 1,
            tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 3600,
        };
        const rawResponseBody = [{ token_address: "token_address", pool_address: "pool_address", prices: [{}] }];

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.api.evm.dex.getPriceHistory({
            chain_id: 1,
            tokens: ["0x6982508145454Ce325dDbE47a25d4ec3d2311933"],
            from: "2026-04-27T00:00:00Z",
            to: "2026-04-27T01:00:00Z",
            interval: 3600,
        });
        expect(response).toEqual(rawResponseBody);
    });

    test("getPriceHistory (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceHistory({
                chain_id: 1,
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.BadRequestError);
    });

    test("getPriceHistory (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceHistory({
                chain_id: 1,
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.UnauthorizedError);
    });

    test("getPriceHistory (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceHistory({
                chain_id: 1,
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.ForbiddenError);
    });

    test("getPriceHistory (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceHistory({
                chain_id: 1,
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.TooManyRequestsError);
    });

    test("getPriceHistory (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PrismClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { chain_id: 1, from: "2024-01-15T09:30:00Z", interval: 1 };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/evm/dex/prices/get-price-history")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.api.evm.dex.getPriceHistory({
                chain_id: 1,
                from: "2024-01-15T09:30:00Z",
                interval: 1,
            });
        }).rejects.toThrow(Prism.api.InternalServerError);
    });
});
