// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions } from "../../../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../../../BaseClient.js";
import { DexClient } from "../resources/dex/client/Client.js";

export declare namespace SolanaClient {
    export type Options = BaseClientOptions;
}

export class SolanaClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<SolanaClient.Options>;
    protected _dex: DexClient | undefined;

    constructor(options: SolanaClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get dex(): DexClient {
        return (this._dex ??= new DexClient(this._options));
    }
}
