/* tslint:disable */
/* eslint-disable */
/**
 * Prism Refract API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetPortfolioRequest,
  GetPriceCandlesRequest,
  GetPriceHistoryRequest,
  GetPriceRequest,
  GetPriceStatsRequest,
  GetSwaps200Response,
  GetSwapsRequest,
  GetTokenProfileRequest,
  GetTokenProfilesByCreatorRequest,
  GetTokenProfilesRequest,
  GetTrades200Response,
  GetTradesRequest,
  GetWalletProfileRequest,
  GetWalletProfilesRequest,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject3,
  InlineObject4,
  SearchSolanaDexTokenProfiles200Response,
  SearchSolanaDexTokenProfilesRequest,
  SearchSolanaDexWalletProfiles200Response,
  SearchSolanaDexWalletProfilesRequest,
  SolanaDexPortfolio,
  SolanaDexPrice,
  SolanaDexPriceCandle,
  SolanaDexPriceHistory,
  SolanaDexPriceStats,
  SolanaDexTokenProfile,
  SolanaDexWalletProfile,
} from '../models/index';

export interface GetPortfolioOperationRequest {
    getPortfolioRequest?: GetPortfolioRequest;
}

export interface GetPriceOperationRequest {
    getPriceRequest?: GetPriceRequest;
}

export interface GetPriceCandlesOperationRequest {
    getPriceCandlesRequest?: GetPriceCandlesRequest;
}

export interface GetPriceHistoryOperationRequest {
    getPriceHistoryRequest?: GetPriceHistoryRequest;
}

export interface GetPriceStatsOperationRequest {
    getPriceStatsRequest?: GetPriceStatsRequest;
}

export interface GetSwapsOperationRequest {
    getSwapsRequest?: GetSwapsRequest;
}

export interface GetTokenProfileOperationRequest {
    getTokenProfileRequest?: GetTokenProfileRequest;
}

export interface GetTokenProfilesOperationRequest {
    getTokenProfilesRequest?: GetTokenProfilesRequest;
}

export interface GetTokenProfilesByCreatorOperationRequest {
    getTokenProfilesByCreatorRequest?: GetTokenProfilesByCreatorRequest;
}

export interface GetTradesOperationRequest {
    getTradesRequest?: GetTradesRequest;
}

export interface GetWalletProfileOperationRequest {
    getWalletProfileRequest?: GetWalletProfileRequest;
}

export interface GetWalletProfilesOperationRequest {
    getWalletProfilesRequest?: GetWalletProfilesRequest;
}

export interface SearchSolanaDexTokenProfilesOperationRequest {
    searchSolanaDexTokenProfilesRequest?: SearchSolanaDexTokenProfilesRequest;
}

export interface SearchSolanaDexWalletProfilesOperationRequest {
    searchSolanaDexWalletProfilesRequest?: SearchSolanaDexWalletProfilesRequest;
}

/**
 * SolanaDEXApi - interface
 * 
 * @export
 * @interface SolanaDEXApiInterface
 */
export interface SolanaDEXApiInterface {
    /**
     * Returns the portfolio for a specific wallet.
     * @summary Get Portfolio
     * @param {GetPortfolioRequest} [getPortfolioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getPortfolioRaw(requestParameters: GetPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexPortfolio>>;

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    getPortfolio(requestParameters: GetPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexPortfolio>;

    /**
     * Returns prices for one or more tokens.
     * @summary Get Price
     * @param {GetPriceRequest} [getPriceRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getPriceRaw(requestParameters: GetPriceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPrice>>>;

    /**
     * Returns prices for one or more tokens.
     * Get Price
     */
    getPrice(requestParameters: GetPriceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPrice>>;

    /**
     * Returns price candles for a specific token.
     * @summary Get Price Candles
     * @param {GetPriceCandlesRequest} [getPriceCandlesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getPriceCandlesRaw(requestParameters: GetPriceCandlesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceCandle>>>;

    /**
     * Returns price candles for a specific token.
     * Get Price Candles
     */
    getPriceCandles(requestParameters: GetPriceCandlesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceCandle>>;

    /**
     * Returns price history for one or more tokens.
     * @summary Get Price History
     * @param {GetPriceHistoryRequest} [getPriceHistoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getPriceHistoryRaw(requestParameters: GetPriceHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceHistory>>>;

    /**
     * Returns price history for one or more tokens.
     * Get Price History
     */
    getPriceHistory(requestParameters: GetPriceHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceHistory>>;

    /**
     * Returns price stats for one or more tokens.
     * @summary Get Price Stats
     * @param {GetPriceStatsRequest} [getPriceStatsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getPriceStatsRaw(requestParameters: GetPriceStatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceStats>>>;

    /**
     * Returns price stats for one or more tokens.
     * Get Price Stats
     */
    getPriceStats(requestParameters: GetPriceStatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceStats>>;

    /**
     * Returns swaps for a wallet, token or both.
     * @summary Get Swaps
     * @param {GetSwapsRequest} [getSwapsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getSwapsRaw(requestParameters: GetSwapsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSwaps200Response>>;

    /**
     * Returns swaps for a wallet, token or both.
     * Get Swaps
     */
    getSwaps(requestParameters: GetSwapsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSwaps200Response>;

    /**
     * Returns the profile for a specific token.
     * @summary Get Profile
     * @param {GetTokenProfileRequest} [getTokenProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfileRaw(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexTokenProfile>>;

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    getTokenProfile(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexTokenProfile>;

    /**
     * Returns profiles for one or more tokens.
     * @summary Get Multiple Profiles
     * @param {GetTokenProfilesRequest} [getTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfilesRaw(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexTokenProfile>>>;

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    getTokenProfiles(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexTokenProfile>>;

    /**
     * Returns token profiles for a specific creator.
     * @summary Get Profiles by Creator
     * @param {GetTokenProfilesByCreatorRequest} [getTokenProfilesByCreatorRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfilesByCreatorRaw(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexTokenProfile>>>;

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    getTokenProfilesByCreator(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexTokenProfile>>;

    /**
     * Returns trades for a wallet, token or both.
     * @summary Get Trades
     * @param {GetTradesRequest} [getTradesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTradesRaw(requestParameters: GetTradesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTrades200Response>>;

    /**
     * Returns trades for a wallet, token or both.
     * Get Trades
     */
    getTrades(requestParameters: GetTradesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTrades200Response>;

    /**
     * Returns a wallet profile for a specific wallet.
     * @summary Get Profile
     * @param {GetWalletProfileRequest} [getWalletProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletProfileRaw(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexWalletProfile>>;

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    getWalletProfile(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexWalletProfile>;

    /**
     * Returns profiles for one or more wallets.
     * @summary Get Multiple Profiles
     * @param {GetWalletProfilesRequest} [getWalletProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletProfilesRaw(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexWalletProfile>>>;

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    getWalletProfiles(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexWalletProfile>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * @summary Search Profiles
     * @param {SearchSolanaDexTokenProfilesRequest} [searchSolanaDexTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    searchSolanaDexTokenProfilesRaw(requestParameters: SearchSolanaDexTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaDexTokenProfiles200Response>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    searchSolanaDexTokenProfiles(requestParameters: SearchSolanaDexTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaDexTokenProfiles200Response>;

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * @summary Search Profiles
     * @param {SearchSolanaDexWalletProfilesRequest} [searchSolanaDexWalletProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    searchSolanaDexWalletProfilesRaw(requestParameters: SearchSolanaDexWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaDexWalletProfiles200Response>>;

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    searchSolanaDexWalletProfiles(requestParameters: SearchSolanaDexWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaDexWalletProfiles200Response>;

}

/**
 * 
 */
export class SolanaDEXApi extends runtime.BaseAPI implements SolanaDEXApiInterface {

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getPortfolioRaw(requestParameters: GetPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexPortfolio>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/portfolios/get-portfolio`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getPortfolioRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getPortfolio(requestParameters: GetPortfolioOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexPortfolio> {
        const response = await this.getPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns prices for one or more tokens.
     * Get Price
     */
    async getPriceRaw(requestParameters: GetPriceOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPrice>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/prices/get-price`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getPriceRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns prices for one or more tokens.
     * Get Price
     */
    async getPrice(requestParameters: GetPriceOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPrice>> {
        const response = await this.getPriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns price candles for a specific token.
     * Get Price Candles
     */
    async getPriceCandlesRaw(requestParameters: GetPriceCandlesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceCandle>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/prices/get-price-candles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getPriceCandlesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns price candles for a specific token.
     * Get Price Candles
     */
    async getPriceCandles(requestParameters: GetPriceCandlesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceCandle>> {
        const response = await this.getPriceCandlesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns price history for one or more tokens.
     * Get Price History
     */
    async getPriceHistoryRaw(requestParameters: GetPriceHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceHistory>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/prices/get-price-history`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getPriceHistoryRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns price history for one or more tokens.
     * Get Price History
     */
    async getPriceHistory(requestParameters: GetPriceHistoryOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceHistory>> {
        const response = await this.getPriceHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns price stats for one or more tokens.
     * Get Price Stats
     */
    async getPriceStatsRaw(requestParameters: GetPriceStatsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexPriceStats>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/prices/get-price-stats`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getPriceStatsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns price stats for one or more tokens.
     * Get Price Stats
     */
    async getPriceStats(requestParameters: GetPriceStatsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexPriceStats>> {
        const response = await this.getPriceStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns swaps for a wallet, token or both.
     * Get Swaps
     */
    async getSwapsRaw(requestParameters: GetSwapsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSwaps200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/swaps/get-swaps`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getSwapsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns swaps for a wallet, token or both.
     * Get Swaps
     */
    async getSwaps(requestParameters: GetSwapsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSwaps200Response> {
        const response = await this.getSwapsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getTokenProfileRaw(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexTokenProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/solana/dex/profiles/tokens/get-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfileRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getTokenProfile(requestParameters: GetTokenProfileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexTokenProfile> {
        const response = await this.getTokenProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getTokenProfilesRaw(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/solana/dex/profiles/tokens/get-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getTokenProfiles(requestParameters: GetTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexTokenProfile>> {
        const response = await this.getTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getTokenProfilesByCreatorRaw(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/profiles/tokens/get-profiles-by-creator`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfilesByCreatorRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getTokenProfilesByCreator(requestParameters: GetTokenProfilesByCreatorOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexTokenProfile>> {
        const response = await this.getTokenProfilesByCreatorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns trades for a wallet, token or both.
     * Get Trades
     */
    async getTradesRaw(requestParameters: GetTradesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTrades200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/trades/get-trades`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTradesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns trades for a wallet, token or both.
     * Get Trades
     */
    async getTrades(requestParameters: GetTradesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTrades200Response> {
        const response = await this.getTradesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    async getWalletProfileRaw(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaDexWalletProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/profiles/wallets/get-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletProfileRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    async getWalletProfile(requestParameters: GetWalletProfileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaDexWalletProfile> {
        const response = await this.getWalletProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    async getWalletProfilesRaw(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaDexWalletProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/profiles/wallets/get-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    async getWalletProfiles(requestParameters: GetWalletProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaDexWalletProfile>> {
        const response = await this.getWalletProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaDexTokenProfilesRaw(requestParameters: SearchSolanaDexTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaDexTokenProfiles200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/profiles/tokens/search-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchSolanaDexTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaDexTokenProfiles(requestParameters: SearchSolanaDexTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaDexTokenProfiles200Response> {
        const response = await this.searchSolanaDexTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaDexWalletProfilesRaw(requestParameters: SearchSolanaDexWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaDexWalletProfiles200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/profiles/wallets/search-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchSolanaDexWalletProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaDexWalletProfiles(requestParameters: SearchSolanaDexWalletProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaDexWalletProfiles200Response> {
        const response = await this.searchSolanaDexWalletProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
