/* tslint:disable */
/* eslint-disable */
/**
 * Prism Refract API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  FilterWalletPositionOverviewsRequest,
  GetWalletOverviewHistoryRequest,
  GetWalletOverviewRequest,
  GetWalletOverviewsRequest,
  GetWalletPortfolioRequest,
  GetWalletPositionOverviewsByTokensRequest,
  GetWalletPositionOverviewsByWalletsRequest,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject3,
  InlineObject4,
  SearchWalletOverviews200Response,
  SearchWalletOverviewsRequest,
  WalletOverview,
  WalletOverviewHistoryInner,
  WalletPortfolio,
  WalletTokenOverview,
} from '../models/index';

export interface FilterWalletPositionOverviewsOperationRequest {
    filterWalletPositionOverviewsRequest?: FilterWalletPositionOverviewsRequest;
}

export interface GetWalletOverviewOperationRequest {
    getWalletOverviewRequest?: GetWalletOverviewRequest;
}

export interface GetWalletOverviewHistoryOperationRequest {
    getWalletOverviewHistoryRequest?: GetWalletOverviewHistoryRequest;
}

export interface GetWalletOverviewsOperationRequest {
    getWalletOverviewsRequest?: GetWalletOverviewsRequest;
}

export interface GetWalletPortfolioOperationRequest {
    getWalletPortfolioRequest?: GetWalletPortfolioRequest;
}

export interface GetWalletPositionOverviewsByTokensOperationRequest {
    getWalletPositionOverviewsByTokensRequest?: GetWalletPositionOverviewsByTokensRequest;
}

export interface GetWalletPositionOverviewsByWalletsOperationRequest {
    getWalletPositionOverviewsByWalletsRequest?: GetWalletPositionOverviewsByWalletsRequest;
}

export interface SearchWalletOverviewsOperationRequest {
    searchWalletOverviewsRequest?: SearchWalletOverviewsRequest;
}

/**
 * SolanaWalletsApi - interface
 * 
 * @export
 * @interface SolanaWalletsApiInterface
 */
export interface SolanaWalletsApiInterface {
    /**
     * Filter and sort position overviews for a specific wallet based on specified metrics and conditions.  Enables flexible aggregation of position overviews by scope, such as recently traded, most profitable, highest risk, and more. 
     * @summary Filter Position Overviews
     * @param {FilterWalletPositionOverviewsRequest} [filterWalletPositionOverviewsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    filterWalletPositionOverviewsRaw(requestParameters: FilterWalletPositionOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>>;

    /**
     * Filter and sort position overviews for a specific wallet based on specified metrics and conditions.  Enables flexible aggregation of position overviews by scope, such as recently traded, most profitable, highest risk, and more. 
     * Filter Position Overviews
     */
    filterWalletPositionOverviews(requestParameters: FilterWalletPositionOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>>;

    /**
     * Returns a wallet overview for a specific wallet.
     * @summary Get Overview
     * @param {GetWalletOverviewRequest} [getWalletOverviewRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletOverviewRaw(requestParameters: GetWalletOverviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletOverview>>;

    /**
     * Returns a wallet overview for a specific wallet.
     * Get Overview
     */
    getWalletOverview(requestParameters: GetWalletOverviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletOverview>;

    /**
     * Returns historical overview for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * @summary Get Overview History
     * @param {GetWalletOverviewHistoryRequest} [getWalletOverviewHistoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletOverviewHistoryRaw(requestParameters: GetWalletOverviewHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletOverviewHistoryInner>>>;

    /**
     * Returns historical overview for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Overview History
     */
    getWalletOverviewHistory(requestParameters: GetWalletOverviewHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletOverviewHistoryInner>>;

    /**
     * Returns overviews for one or more wallets.
     * @summary Get Multiple Overviews
     * @param {GetWalletOverviewsRequest} [getWalletOverviewsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletOverviewsRaw(requestParameters: GetWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletOverview>>>;

    /**
     * Returns overviews for one or more wallets.
     * Get Multiple Overviews
     */
    getWalletOverviews(requestParameters: GetWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletOverview>>;

    /**
     * Returns the portfolio for a specific wallet.
     * @summary Get Portfolio
     * @param {GetWalletPortfolioRequest} [getWalletPortfolioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletPortfolioRaw(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletPortfolio>>;

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    getWalletPortfolio(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletPortfolio>;

    /**
     * Returns wallet position overviews for a specific wallet, broken down by selected tokens. Useful for analyzing how a wallet performs across different tokens.
     * @summary Get Position Overviews by Tokens
     * @param {GetWalletPositionOverviewsByTokensRequest} [getWalletPositionOverviewsByTokensRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletPositionOverviewsByTokensRaw(requestParameters: GetWalletPositionOverviewsByTokensOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>>;

    /**
     * Returns wallet position overviews for a specific wallet, broken down by selected tokens. Useful for analyzing how a wallet performs across different tokens.
     * Get Position Overviews by Tokens
     */
    getWalletPositionOverviewsByTokens(requestParameters: GetWalletPositionOverviewsByTokensOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>>;

    /**
     * Returns wallet position overviews for a specific token, broken down by selected wallets. Useful for analyzing how different wallets perform across the same token.
     * @summary Get Position Overviews by Wallets
     * @param {GetWalletPositionOverviewsByWalletsRequest} [getWalletPositionOverviewsByWalletsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    getWalletPositionOverviewsByWalletsRaw(requestParameters: GetWalletPositionOverviewsByWalletsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>>;

    /**
     * Returns wallet position overviews for a specific token, broken down by selected wallets. Useful for analyzing how different wallets perform across the same token.
     * Get Position Overviews by Wallets
     */
    getWalletPositionOverviewsByWallets(requestParameters: GetWalletPositionOverviewsByWalletsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>>;

    /**
     * Search and filter wallet overviews based on specified metrics and conditions.
     * @summary Search Overviews
     * @param {SearchWalletOverviewsRequest} [searchWalletOverviewsRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaWalletsApiInterface
     */
    searchWalletOverviewsRaw(requestParameters: SearchWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchWalletOverviews200Response>>;

    /**
     * Search and filter wallet overviews based on specified metrics and conditions.
     * Search Overviews
     */
    searchWalletOverviews(requestParameters: SearchWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchWalletOverviews200Response>;

}

/**
 * 
 */
export class SolanaWalletsApi extends runtime.BaseAPI implements SolanaWalletsApiInterface {

    /**
     * Filter and sort position overviews for a specific wallet based on specified metrics and conditions.  Enables flexible aggregation of position overviews by scope, such as recently traded, most profitable, highest risk, and more. 
     * Filter Position Overviews
     */
    async filterWalletPositionOverviewsRaw(requestParameters: FilterWalletPositionOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/filter-position-overviews`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['filterWalletPositionOverviewsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Filter and sort position overviews for a specific wallet based on specified metrics and conditions.  Enables flexible aggregation of position overviews by scope, such as recently traded, most profitable, highest risk, and more. 
     * Filter Position Overviews
     */
    async filterWalletPositionOverviews(requestParameters: FilterWalletPositionOverviewsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>> {
        const response = await this.filterWalletPositionOverviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a wallet overview for a specific wallet.
     * Get Overview
     */
    async getWalletOverviewRaw(requestParameters: GetWalletOverviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletOverview>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-overview`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletOverviewRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a wallet overview for a specific wallet.
     * Get Overview
     */
    async getWalletOverview(requestParameters: GetWalletOverviewOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletOverview> {
        const response = await this.getWalletOverviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns historical overview for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Overview History
     */
    async getWalletOverviewHistoryRaw(requestParameters: GetWalletOverviewHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletOverviewHistoryInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-overview-history`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletOverviewHistoryRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns historical overview for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Overview History
     */
    async getWalletOverviewHistory(requestParameters: GetWalletOverviewHistoryOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletOverviewHistoryInner>> {
        const response = await this.getWalletOverviewHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns overviews for one or more wallets.
     * Get Multiple Overviews
     */
    async getWalletOverviewsRaw(requestParameters: GetWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletOverview>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-overviews`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletOverviewsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns overviews for one or more wallets.
     * Get Multiple Overviews
     */
    async getWalletOverviews(requestParameters: GetWalletOverviewsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletOverview>> {
        const response = await this.getWalletOverviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getWalletPortfolioRaw(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WalletPortfolio>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-portfolio`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletPortfolioRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getWalletPortfolio(requestParameters: GetWalletPortfolioOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WalletPortfolio> {
        const response = await this.getWalletPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns wallet position overviews for a specific wallet, broken down by selected tokens. Useful for analyzing how a wallet performs across different tokens.
     * Get Position Overviews by Tokens
     */
    async getWalletPositionOverviewsByTokensRaw(requestParameters: GetWalletPositionOverviewsByTokensOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-position-overviews-by-tokens`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletPositionOverviewsByTokensRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns wallet position overviews for a specific wallet, broken down by selected tokens. Useful for analyzing how a wallet performs across different tokens.
     * Get Position Overviews by Tokens
     */
    async getWalletPositionOverviewsByTokens(requestParameters: GetWalletPositionOverviewsByTokensOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>> {
        const response = await this.getWalletPositionOverviewsByTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns wallet position overviews for a specific token, broken down by selected wallets. Useful for analyzing how different wallets perform across the same token.
     * Get Position Overviews by Wallets
     */
    async getWalletPositionOverviewsByWalletsRaw(requestParameters: GetWalletPositionOverviewsByWalletsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WalletTokenOverview>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/get-position-overviews-by-wallets`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletPositionOverviewsByWalletsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns wallet position overviews for a specific token, broken down by selected wallets. Useful for analyzing how different wallets perform across the same token.
     * Get Position Overviews by Wallets
     */
    async getWalletPositionOverviewsByWallets(requestParameters: GetWalletPositionOverviewsByWalletsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WalletTokenOverview>> {
        const response = await this.getWalletPositionOverviewsByWalletsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter wallet overviews based on specified metrics and conditions.
     * Search Overviews
     */
    async searchWalletOverviewsRaw(requestParameters: SearchWalletOverviewsOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchWalletOverviews200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/wallets/search-overviews`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchWalletOverviewsRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter wallet overviews based on specified metrics and conditions.
     * Search Overviews
     */
    async searchWalletOverviews(requestParameters: SearchWalletOverviewsOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchWalletOverviews200Response> {
        const response = await this.searchWalletOverviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
