/* tslint:disable */
/* eslint-disable */
/**
 * Prism Refract API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSolanaTokenPricesRequest,
  GetSolanaTokenProfileRequest,
  GetSolanaTokenProfilesByCreatorRequest,
  GetSolanaTokenProfilesRequest,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject3,
  InlineObject4,
  SearchSolanaTokenProfilesRequest,
  SolanaTokenPrice,
  SolanaTokenProfile,
} from '../models/index';

export interface GetSolanaTokenPricesOperationRequest {
    getSolanaTokenPricesRequest?: GetSolanaTokenPricesRequest;
}

export interface GetSolanaTokenProfileOperationRequest {
    getSolanaTokenProfileRequest?: GetSolanaTokenProfileRequest;
}

export interface GetSolanaTokenProfilesOperationRequest {
    getSolanaTokenProfilesRequest?: GetSolanaTokenProfilesRequest;
}

export interface GetSolanaTokenProfilesByCreatorOperationRequest {
    getSolanaTokenProfilesByCreatorRequest?: GetSolanaTokenProfilesByCreatorRequest;
}

export interface SearchSolanaTokenProfilesOperationRequest {
    searchSolanaTokenProfilesRequest?: SearchSolanaTokenProfilesRequest;
}

/**
 * SolanaTokensApi - interface
 * 
 * @export
 * @interface SolanaTokensApiInterface
 */
export interface SolanaTokensApiInterface {
    /**
     * Returns prices for one or more tokens.
     * @summary Get Prices
     * @param {GetSolanaTokenPricesRequest} [getSolanaTokenPricesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaTokensApiInterface
     */
    getSolanaTokenPricesRaw(requestParameters: GetSolanaTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenPrice>>>;

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    getSolanaTokenPrices(requestParameters: GetSolanaTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenPrice>>;

    /**
     * Returns the profile for a specific token.
     * @summary Get Profile
     * @param {GetSolanaTokenProfileRequest} [getSolanaTokenProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaTokensApiInterface
     */
    getSolanaTokenProfileRaw(requestParameters: GetSolanaTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaTokenProfile>>;

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    getSolanaTokenProfile(requestParameters: GetSolanaTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaTokenProfile>;

    /**
     * Returns profiles for one or more tokens.
     * @summary Get Multiple Profiles
     * @param {GetSolanaTokenProfilesRequest} [getSolanaTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaTokensApiInterface
     */
    getSolanaTokenProfilesRaw(requestParameters: GetSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    getSolanaTokenProfiles(requestParameters: GetSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

    /**
     * Returns token profiles for a specific creator.
     * @summary Get Profiles by Creator
     * @param {GetSolanaTokenProfilesByCreatorRequest} [getSolanaTokenProfilesByCreatorRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaTokensApiInterface
     */
    getSolanaTokenProfilesByCreatorRaw(requestParameters: GetSolanaTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    getSolanaTokenProfilesByCreator(requestParameters: GetSolanaTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * @summary Search Profiles
     * @param {SearchSolanaTokenProfilesRequest} [searchSolanaTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaTokensApiInterface
     */
    searchSolanaTokenProfilesRaw(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    searchSolanaTokenProfiles(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

}

/**
 * 
 */
export class SolanaTokensApi extends runtime.BaseAPI implements SolanaTokensApiInterface {

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    async getSolanaTokenPricesRaw(requestParameters: GetSolanaTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenPrice>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/tokens/get-prices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getSolanaTokenPricesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    async getSolanaTokenPrices(requestParameters: GetSolanaTokenPricesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenPrice>> {
        const response = await this.getSolanaTokenPricesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getSolanaTokenProfileRaw(requestParameters: GetSolanaTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaTokenProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/solana/tokens/get-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getSolanaTokenProfileRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getSolanaTokenProfile(requestParameters: GetSolanaTokenProfileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaTokenProfile> {
        const response = await this.getSolanaTokenProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getSolanaTokenProfilesRaw(requestParameters: GetSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/solana/tokens/get-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getSolanaTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getSolanaTokenProfiles(requestParameters: GetSolanaTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.getSolanaTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getSolanaTokenProfilesByCreatorRaw(requestParameters: GetSolanaTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/tokens/get-profiles-by-creator`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getSolanaTokenProfilesByCreatorRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getSolanaTokenProfilesByCreator(requestParameters: GetSolanaTokenProfilesByCreatorOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.getSolanaTokenProfilesByCreatorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaTokenProfilesRaw(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/solana/tokens/search-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchSolanaTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaTokenProfiles(requestParameters: SearchSolanaTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.searchSolanaTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
