/* tslint:disable */
/* eslint-disable */
/**
 * Prism Refract API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetTokenPricesRequest,
  GetTokenProfileRequest,
  GetTokenProfilesByCreatorRequest,
  GetTokenProfilesRequest,
  GetWalletPortfolioRequest,
  GetWalletProfileHistoryRequest,
  GetWalletProfileRequest,
  GetWalletProfilesRequest,
  InlineObject,
  InlineObject1,
  InlineObject2,
  InlineObject3,
  InlineObject4,
  SearchSolanaTokenProfilesRequest,
  SearchSolanaWalletProfiles200Response,
  SearchSolanaWalletProfilesRequest,
  SolanaTokenPrice,
  SolanaTokenProfile,
  SolanaWalletPortfolio,
  SolanaWalletProfile,
  SolanaWalletProfileHistoryInner,
} from '../models/index';

export interface GetTokenPricesOperationRequest {
    getTokenPricesRequest?: GetTokenPricesRequest;
}

export interface GetTokenProfileOperationRequest {
    getTokenProfileRequest?: GetTokenProfileRequest;
}

export interface GetTokenProfilesOperationRequest {
    getTokenProfilesRequest?: GetTokenProfilesRequest;
}

export interface GetTokenProfilesByCreatorOperationRequest {
    getTokenProfilesByCreatorRequest?: GetTokenProfilesByCreatorRequest;
}

export interface GetWalletPortfolioOperationRequest {
    getWalletPortfolioRequest?: GetWalletPortfolioRequest;
}

export interface GetWalletProfileOperationRequest {
    getWalletProfileRequest?: GetWalletProfileRequest;
}

export interface GetWalletProfileHistoryOperationRequest {
    getWalletProfileHistoryRequest?: GetWalletProfileHistoryRequest;
}

export interface GetWalletProfilesOperationRequest {
    getWalletProfilesRequest?: GetWalletProfilesRequest;
}

export interface SearchSolanaTokenProfilesOperationRequest {
    searchSolanaTokenProfilesRequest?: SearchSolanaTokenProfilesRequest;
}

export interface SearchSolanaWalletProfilesOperationRequest {
    searchSolanaWalletProfilesRequest?: SearchSolanaWalletProfilesRequest;
}

/**
 * SolanaDEXApi - interface
 * 
 * @export
 * @interface SolanaDEXApiInterface
 */
export interface SolanaDEXApiInterface {
    /**
     * Returns prices for one or more tokens.
     * @summary Get Prices
     * @param {GetTokenPricesRequest} [getTokenPricesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenPricesRaw(requestParameters: GetTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenPrice>>>;

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    getTokenPrices(requestParameters: GetTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenPrice>>;

    /**
     * Returns the profile for a specific token.
     * @summary Get Profile
     * @param {GetTokenProfileRequest} [getTokenProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfileRaw(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaTokenProfile>>;

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    getTokenProfile(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaTokenProfile>;

    /**
     * Returns profiles for one or more tokens.
     * @summary Get Multiple Profiles
     * @param {GetTokenProfilesRequest} [getTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfilesRaw(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    getTokenProfiles(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

    /**
     * Returns token profiles for a specific creator.
     * @summary Get Profiles by Creator
     * @param {GetTokenProfilesByCreatorRequest} [getTokenProfilesByCreatorRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getTokenProfilesByCreatorRaw(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    getTokenProfilesByCreator(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

    /**
     * Returns the portfolio for a specific wallet.
     * @summary Get Portfolio
     * @param {GetWalletPortfolioRequest} [getWalletPortfolioRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletPortfolioRaw(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaWalletPortfolio>>;

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    getWalletPortfolio(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaWalletPortfolio>;

    /**
     * Returns a wallet profile for a specific wallet.
     * @summary Get Profile
     * @param {GetWalletProfileRequest} [getWalletProfileRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletProfileRaw(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaWalletProfile>>;

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    getWalletProfile(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaWalletProfile>;

    /**
     * Returns historical profile for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * @summary Get Profile History
     * @param {GetWalletProfileHistoryRequest} [getWalletProfileHistoryRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletProfileHistoryRaw(requestParameters: GetWalletProfileHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaWalletProfileHistoryInner>>>;

    /**
     * Returns historical profile for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Profile History
     */
    getWalletProfileHistory(requestParameters: GetWalletProfileHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaWalletProfileHistoryInner>>;

    /**
     * Returns profiles for one or more wallets.
     * @summary Get Multiple Profiles
     * @param {GetWalletProfilesRequest} [getWalletProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    getWalletProfilesRaw(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaWalletProfile>>>;

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    getWalletProfiles(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaWalletProfile>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * @summary Search Profiles
     * @param {SearchSolanaTokenProfilesRequest} [searchSolanaTokenProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    searchSolanaTokenProfilesRaw(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>>;

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    searchSolanaTokenProfiles(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>>;

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * @summary Search Profiles
     * @param {SearchSolanaWalletProfilesRequest} [searchSolanaWalletProfilesRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SolanaDEXApiInterface
     */
    searchSolanaWalletProfilesRaw(requestParameters: SearchSolanaWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaWalletProfiles200Response>>;

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    searchSolanaWalletProfiles(requestParameters: SearchSolanaWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaWalletProfiles200Response>;

}

/**
 * 
 */
export class SolanaDEXApi extends runtime.BaseAPI implements SolanaDEXApiInterface {

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    async getTokenPricesRaw(requestParameters: GetTokenPricesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenPrice>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/tokens/get-prices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenPricesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns prices for one or more tokens.
     * Get Prices
     */
    async getTokenPrices(requestParameters: GetTokenPricesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenPrice>> {
        const response = await this.getTokenPricesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getTokenProfileRaw(requestParameters: GetTokenProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaTokenProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/solana/dex/tokens/get-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfileRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the profile for a specific token.
     * Get Profile
     */
    async getTokenProfile(requestParameters: GetTokenProfileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaTokenProfile> {
        const response = await this.getTokenProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getTokenProfilesRaw(requestParameters: GetTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/solana/dex/tokens/get-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns profiles for one or more tokens.
     * Get Multiple Profiles
     */
    async getTokenProfiles(requestParameters: GetTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.getTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getTokenProfilesByCreatorRaw(requestParameters: GetTokenProfilesByCreatorOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/tokens/get-profiles-by-creator`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getTokenProfilesByCreatorRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns token profiles for a specific creator.
     * Get Profiles by Creator
     */
    async getTokenProfilesByCreator(requestParameters: GetTokenProfilesByCreatorOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.getTokenProfilesByCreatorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getWalletPortfolioRaw(requestParameters: GetWalletPortfolioOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaWalletPortfolio>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/wallets/get-portfolio`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletPortfolioRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns the portfolio for a specific wallet.
     * Get Portfolio
     */
    async getWalletPortfolio(requestParameters: GetWalletPortfolioOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaWalletPortfolio> {
        const response = await this.getWalletPortfolioRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    async getWalletProfileRaw(requestParameters: GetWalletProfileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SolanaWalletProfile>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/wallets/get-profile`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletProfileRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns a wallet profile for a specific wallet.
     * Get Profile
     */
    async getWalletProfile(requestParameters: GetWalletProfileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SolanaWalletProfile> {
        const response = await this.getWalletProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns historical profile for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Profile History
     */
    async getWalletProfileHistoryRaw(requestParameters: GetWalletProfileHistoryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaWalletProfileHistoryInner>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/wallets/get-profile-history`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletProfileHistoryRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns historical profile for a specific wallet, aggregated by the selected time frame. Useful for trend analysis and performance tracking over time.
     * Get Profile History
     */
    async getWalletProfileHistory(requestParameters: GetWalletProfileHistoryOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaWalletProfileHistoryInner>> {
        const response = await this.getWalletProfileHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    async getWalletProfilesRaw(requestParameters: GetWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaWalletProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/wallets/get-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['getWalletProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Returns profiles for one or more wallets.
     * Get Multiple Profiles
     */
    async getWalletProfiles(requestParameters: GetWalletProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaWalletProfile>> {
        const response = await this.getWalletProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaTokenProfilesRaw(requestParameters: SearchSolanaTokenProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SolanaTokenProfile>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/tokens/search-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchSolanaTokenProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter token profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaTokenProfiles(requestParameters: SearchSolanaTokenProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SolanaTokenProfile>> {
        const response = await this.searchSolanaTokenProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaWalletProfilesRaw(requestParameters: SearchSolanaWalletProfilesOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSolanaWalletProfiles200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["X-Api-Key"] = await this.configuration.apiKey("X-Api-Key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/solana/dex/wallets/search-profiles`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['searchSolanaWalletProfilesRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * Search and filter wallet profiles based on specified metrics and conditions.
     * Search Profiles
     */
    async searchSolanaWalletProfiles(requestParameters: SearchSolanaWalletProfilesOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSolanaWalletProfiles200Response> {
        const response = await this.searchSolanaWalletProfilesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
