// This file was auto-generated by Fern from our API Definition.

export interface TokenProfilesSubscriptionMessage {
    topic?: string | undefined;
    data?: Record<string, unknown> | undefined;
}
