// This file was auto-generated by Fern from our API Definition.

import type * as ApiClient from "../../../../../../index.js";

/**
 * @example
 *     {
 *         limit: 10,
 *         query: {
 *             text: "cupsey",
 *             fields: ["wallet_address"]
 *         },
 *         sort: {
 *             field: "metrics.7d.cumulative_pnl",
 *             direction: "desc"
 *         },
 *         dynamic_labels: {
 *             "smart": {}
 *         },
 *         options: {
 *             include_metadata: true,
 *             include_labels: true,
 *             include_metrics: ["7d"]
 *         }
 *     }
 */
export interface SearchWalletProfilesDexRequest extends ApiClient.PayloadPagination {
    query?: ApiClient.SolanaDexWalletProfileSearchPayloadQuery;
    filter?: ApiClient.SolanaDexProfileSearchPayloadFilter;
    sort?: ApiClient.SolanaDexProfileSearchPayloadSort;
    dynamic_labels?: ApiClient.SolanaDexProfileSearchPayloadDynamicLabels;
    options?: ApiClient.SolanaDexWalletProfilePayloadOptions;
}
