// This file was auto-generated by Fern from our API Definition.

export const PrismEnvironment = {
    Production: "https://refract.prismapi.io",
} as const;

export type PrismEnvironment = typeof PrismEnvironment.Production;
