// This file was auto-generated by Fern from our API Definition.

export const ApiClientEnvironment = {
    Default: "https://refract.prismapi.io",
} as const;

export type ApiClientEnvironment = typeof ApiClientEnvironment.Default;
