// This file was auto-generated by Fern from our API Definition.

export interface SubscribeWalletTrades {
    method: string;
    topic: string;
    params: SubscribeWalletTrades.Params;
}

export namespace SubscribeWalletTrades {
    export interface Params {
        wallets?: string[] | undefined;
    }
}
