// This file was auto-generated by Fern from our API Definition.

export interface WalletTradesSubscriptionMessage {
    topic?: string | undefined;
    data?: WalletTradesSubscriptionMessage.Data | undefined;
}

export namespace WalletTradesSubscriptionMessage {
    export interface Data {
        id?: number | undefined;
        /** Refer to [Data Sources](/documentation/solana/dex/overview#data-sources) for the list of supported protocols. */
        protocol?: string | undefined;
        swap_type?: Data.SwapType | undefined;
        wallet_address?: string | undefined;
        token_address?: string | undefined;
        quote_address?: string | undefined;
        position_address?: string | undefined;
        direction?: Data.Direction | undefined;
        position_state?: Data.PositionState | undefined;
        token_amount?: number | undefined;
        quote_amount?: number | undefined;
        native_amount?: number | undefined;
        usd_amount?: number | undefined;
        pre_token_balance?: number | undefined;
        post_token_balance?: number | undefined;
        token_price?: number | undefined;
        quote_price?: number | undefined;
        token_mcap?: number | undefined;
        block_slot?: number | undefined;
        block_time?: string | undefined;
        tx_hash?: string | undefined;
    }

    export namespace Data {
        export const SwapType = {
            QuoteToken: "quote_token",
            TokenQuote: "token_quote",
            TokenToken: "token_token",
            QuoteQuote: "quote_quote",
        } as const;
        export type SwapType = (typeof SwapType)[keyof typeof SwapType];
        export const Direction = {
            Buy: "buy",
            Sell: "sell",
        } as const;
        export type Direction = (typeof Direction)[keyof typeof Direction];
        export const PositionState = {
            Open: "open",
            Close: "close",
            Trade: "trade",
        } as const;
        export type PositionState = (typeof PositionState)[keyof typeof PositionState];
    }
}
